export enum ePermission {
  CAN_VIEW = 'CAN_VIEW',
  CAN_CHAT = 'CAN_CHAT',
  CAN_LOGIN = 'CAN_LOGIN',
  CAN_GET_INFO = 'CAN_GET_INFO',
  CAN_DELETE_ACCOUNT = 'CAN_DELETE_ACCOUNT',
  CAN_GET_LIST_ACCOUNT = 'CAN_GET_LIST_ACCOUNT',
}
